# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: BuildIt
  jobs:
  - job: BuildTheCode
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: replacetokens@3
      inputs:
        targetFiles: '**/*.cshtml'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        useLegacyPattern: false
        enableTelemetry: true

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# - stage: TestDeployment
#   jobs:
#   - job: PublishTheCode
#     steps:
#     - task: DownloadBuildArtifacts@0
#       inputs:
#         buildType: 'current'
#         downloadType: 'single'
#         artifactName: 'drop'
#         downloadPath: '$(System.ArtifactsDirectory)'

#     - task: AzureResourceManagerTemplateDeployment@3
#       inputs:
#         deploymentScope: 'Resource Group'
#         azureResourceManagerConnection: 'Azure DevOps 2024 (8b4c1959-38e7-4bd8-8830-1aaf982c36fb)'
#         subscriptionId: '8b4c1959-38e7-4bd8-8830-1aaf982c36fb5'
#         action: 'Create Or Update Resource Group'
#         resourceGroupName: 'azure-devops-2024'
#         location: 'West Europe'
#         templateLocation: 'Linked artifact'
#         csmFile: '$(System.ArtifactsDirectory)/**/WebAppWithSlots-Windows.json'
#         csmParametersFile: '$(System.ArtifactsDirectory)/**/azuredeploy.parameters.json'
#         overrideParameters: '-appName bnkYAML'
#         deploymentMode: 'Incremental'

#     - task: AzureRmWebAppDeployment@4
#       inputs:
#         ConnectionType: 'AzureRM'
#         azureSubscription: 'Azure DevOps 2024 (8b4c1959-38e7-4bd8-8830-1aaf982c36fb)'
#         appType: 'webApp'
#         WebAppName: 'bnkYAML'
#         packageForLinux: '$(System.ArtifactsDirectory)/**/OldDadApp.zip'